config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :conversations, only: [ :index, :show ] do
    resources :messages, only: :create
  end

  resources :pages, only: [:index, :show]
  get "/dashboard", to: 'pages#dashboard'
  resources :runners, only: [:index, :show, :edit, :update] do
    resources :requests, only: [:new, :create]
    resources :events, only: [:new, :create]
    resources :conversations, only: [:create]
  end

  resources :requests, only: [:destroy]

  resources :requests do
    post 'approve', to: 'requests#approve'
    post 'reject', to: 'requests#reject'
  end

  resource :profile, only: [:edit, :update, :show]

  resources :tracks, only: [:index, :show, :new, :create]


  put '/track/:id/like', to: 'tracks#like', as: 'like'
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :likes, dependent: :destroy
  def liked?(user)
    !!self.likes.find{ |like| like.user_id == user.id}
  end

  include PgSearch::Model
  pg_search_scope :search_by_address,
                  against: [:address],
                  using: {
                    tsearch: { prefix: true } 
                  }
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index]
  def index
    @tracks = policy_scope(Track).order(created_at: :desc)

    if params[:query].present?
      @tracks = Track.where("name ILIKE ?", "%#{params[:query]}%")

    else
      @tracks = policy_scope(Track).order(created_at: :desc)
    end

    @markers = @tracks.geocoded.map do |track|
      {
        lat: track.latitude,
        lng: track.longitude,
        infoWindow: render_to_string(partial: "shared/info_window_track", locals: { track: track }),
        id: track.id,
        image_url: helpers.asset_url('marker.png')
      }
    end

    @current_tab = "Tracks"
    if current_user
    @received_requests = current_user.received_requests
    @pending_requests =[]

    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end
  end
  end

  def show
    @track = Track.find(params[:id])
    @received_requests = current_user.received_requests
    @sent_requests = current_user.sent_requests
    @pending_requests =[]
    @current_tab = "Tracks"
    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end
    authorize @track
  end

  def new
    @track = Track.new

    @current_tab = "Tracks"
    @received_requests = current_user.received_requests
    @pending_requests =[]

    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end

    authorize @track
  end


  def create
    @track = Track.new(track_params)
    @track.user = current_user

    @current_tab = "Tracks"
    @received_requests = current_user.received_requests
    @pending_requests =[]

    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end

    if @track.save
      redirect_to tracks_path
    else
      render :new
    end

    authorize @track
  end

  def like
    @track = Track.find(params[:id])
    Like.create(user_id: current_user.id, track_id: @track.id)
  end

  private

  def track_params
    params.require(:track).permit(:name, :description, :keyword, :address, :image)
  end
end

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/index.html.erb
<div class="map-page">

  <div class="container card-container">
    <h1 class="header-style"><i class="fas fa-map-marked-alt"></i> Tracks Near Me</h1>


    <div class="form-row mb-5">

      <%= form_tag tracks_path, class:"form-inline mt-3 mb-3", method: :get do%>

        <div>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search",
          autocomplete: 'off'
        %>

        <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
        <%= link_to "Share your own track", new_track_path, class: "add-track" %>
      </div>
    </div>

    <div class="row">
      <div class="cards col-md-6 tracks-list">

        <% @tracks.each do |track| %>
          <%= link_to(track_path(track.id)) do%>
          <div class="track-card" data-marker-id="<%= track.id %>">
            <%= cl_image_tag track.image.key, crop: :fill, class: "track-img" %>

            <div class="card-body">
              <h3><%= track.name%></h3>
              <p><%= track.description.split(/\W+/)[0..14 ].join(" ")%></p>
              <p class="track-link-hover">. . . more</p>
              <% track.keyword.each do |keyword| %>
                <div class="track-keywords">
                  <h6 class="one-keyword">#<%= keyword %></h6>
                </div>
              <% end %>
            </div>
            </div>
          <% end %>
          <% end %>
      </div>

      <div class="col-md-6 track-map">
        <div id="map"
              style="width: 100%; height: 97vh;"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>


    </div>
  </div>
</div>

app/views/tracks/new.html.erb
<div class="event-page">
  <div class="event-container">
    <h1 class="event-header">Share your own track</h1>

    <%= simple_form_for @track do |f| %>
      <%= f.input :name, as: :string %>
      <%= f.input :address, as: :string %>
      <%= f.input :description, as: :text %>
      <%= f.input :keyword, as: :text %>
      <%= f.input :image, as: :file %>
      <%= f.submit "Add a new track", class: "event-button" %>
    <% end %>
  </div>
</div>

app/views/tracks/show.html.erb
<div class="container">
  <h1 class="track-name"><%= @track.name %> <i class="fas fa-map-marker-alt"></i></h1>
  <hr class="my-3"/>
  <div class="row">
    <div class="description-box col-md-6">
      <p class="description"><%= @track.description %></p>
      <p class="keyword-title mx-2"><i class="fa fa-hashtag" aria-hidden="true"></i>Keywords</p>
      <% @track.keyword.each do |keyword| %>
        <div class="track-keywords">
          <h6 class="one-keyword">#<%= keyword %></h6>
        </div>
      <% end %>
      <br>

      <input id="foo" value="<%= track_url(@track) %>">
      <br>
      <button class="btn btn-md btn-primary copy-button mx-2" data-clipboard-target="#foo">Copy Link</button>
      <button class="btn btn-md btn-primary buddy-request-button" id="track-click">Send link to buddy</button>
      <div class="small-popup-card" id="track-popup-card">
        <span class="close">x</span>
        <h4 class="mb-4">Choose your buddy</h4>
        <% @received_requests.each do |request| %>
          <% if request.status == 'Approved' %>
            <div class="buddy-link">
              <%= form_with(url: "/runners/#{request.sender.id}/conversations?", method: "post") do %>
              <%= submit_tag("Chat with #{request.sender.first_name}", class: "chat-button mt-2") %>
              <% end %>
            </div>
          <% else %>
          <% end %>
        <% end %>
        <% @sent_requests.each do |request| %>
          <% if request.status == 'Approved' %>
            <div class="buddy-link">
              <%= form_with(url: "/runners/#{request.receiver.id}/conversations?", method: "post") do %>
              <%= submit_tag("Chat with #{request.receiver.first_name}", class: "chat-button mt-2") %>
              <% end %>
            </div>
          <% else %>
          <% end %>
        <% end %>
      </div>

    </div>

    <div class="col-md-6 track-images">
      <%= cl_image_tag @track.image.key, crop: :fill, class: "track-image" %>
    </div>
  </div>
</div>