config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :conversations, only: [ :index, :show ] do
    resources :messages, only: :create
  end

  resources :pages, only: [:index, :show]
  get "/dashboard", to: 'pages#dashboard'
  resources :runners, only: [:index, :show, :edit, :update] do
    resources :requests, only: [:new, :create]
    resources :events, only: [:new, :create]
    resources :conversations, only: [:create]
  end

  resources :requests, only: [:destroy]

  resources :requests do
    post 'approve', to: 'requests#approve'
    post 'reject', to: 'requests#reject'
  end

  resource :profile, only: [:edit, :update, :show]

  resources :tracks, only: [:index, :show, :new, :create]


  put '/track/:id/like', to: 'tracks#like', as: 'like'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, foreign_key: :user1_id, class_name: 'User'
  belongs_to :user2, foreign_key: :user2_id, class_name: 'User'
  has_many :messages, dependent: :destroy
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout "message"

  def index
    @conversations = policy_scope(Conversation).order(created_at: :desc)
    @user = current_user
    @current_tab = "Messages"
    @received_requests = current_user.received_requests
    @pending_requests =[]

    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end
  end

  def show
    @user = current_user
    @conversations = policy_scope(Conversation).order(created_at: :desc)
    @conversation = Conversation.find(params[:id])
    @message = Message.new
    if @conversation.user1 == current_user
      @partner = @conversation.user2
      @current_tab = @conversation.user2
    else
      @partner = @conversation.user1
      @current_tab = @conversation.user1

    end
    @current_tab = "Messages"
    @received_requests = current_user.received_requests
    @pending_requests =[]

    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end

    authorize @conversation
  end

  def create
    @user = current_user
    @partner = User.find(params[:runner_id])
    @conversation = Conversation.find_by(user1: current_user, user2: @partner) || Conversation.find_by(user2: current_user, user1: @partner)

    if @conversation.nil?
      @conversation = Conversation.create(user1: current_user, user2: @partner)
    end

    authorize @conversation
    redirect_to @conversation
  end

end

app/views/conversations/index.html.erb
<div class="chat-body-index">
<div class="container">
  <h1 class="header-style text-center"><i class="fa fa-comments" aria-hidden="true"></i> 
  Chat with your running buddies</h1>

  <div class="chat-page-index">
    <div class="chat-bar-index">
      <div class="chat-bar-title">
        <h3>My buddies</h3>
      </div>
      <% @conversations.each do |conversation| %>
        <% if @user.id == conversation.user1_id %>
          <div class="chatbar-line">
            <%= cl_image_tag conversation.user2.image.key, height: 40, width: 40, crop: :fill, class: "chat-avatar-big" %>
            <%= link_to "#{conversation.user2.first_name} #{conversation.user2.last_name}", conversation %>
          </div>
        <% elsif @user.id == conversation.user2_id %>
          <div class="chatbar-line">
            <%= cl_image_tag conversation.user1.image.key, height: 40, width: 40, crop: :fill, class: "chat-avatar-big" %>
            <%= link_to "#{conversation.user1.first_name} #{conversation.user1.last_name}", conversation %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/conversations/show.html.erb
<div class="chat-body">
<div class="container">
  <h1 class="header-style text-center"><i class="fa fa-comments" aria-hidden="true"></i> Chat with your running buddies</h1>

  <div class="chat-page">
    <div class="col-md-3">
      <div class="chat-bar">
        <div class="chat-bar-title">
          <h3>My buddies</h3>
        </div>
          <% @conversations.each do |conversation| %>
            <% if @user.id == conversation.user1_id %>
              <div class="chatbar-line <%= 'active' if @current_tab == conversation.user2 %>">
                <%= cl_image_tag conversation.user2.image.key, height: 40, width: 40, crop: :fill, class: "chat-avatar-small" %>
                <%= link_to "#{conversation.user2.first_name} #{conversation.user2.last_name}", conversation %>
              </div>
            <% elsif @user.id == conversation.user2_id %>
              <div class="chatbar-line <%= 'active' if @current_tab == conversation.user1 %>">
                <%= cl_image_tag conversation.user1.image.key, height: 40, width: 40, crop: :fill, class: "chat-avatar-small" %>
                <%= link_to "#{conversation.user1.first_name} #{conversation.user1.last_name}", conversation %>
              </div>
            <% end %>
          <% end %>
      </div>

        <div class="buttons">
          <% if @conversation.user2.first_name == current_user.first_name %>
            <%= link_to " 📆 Add running session with #{@conversation.user1.first_name}", new_runner_event_path(@partner), class: 'calendar-button' %>
          <% else %>
            <%= link_to " 📆 Add running session with #{@conversation.user2.first_name}", new_runner_event_path(@partner), class: 'calendar-button' %>
          <% end %>
        </div>
    </div>


    <div class="chatroom col-md-9">
      <div class="chat-part" id="messages" data-chatroom-id="<%= @conversation.id %>" data-chatroom-id="<%= @conversation.id %>">
        <% @conversation.messages.each do |message| %>
        <%= render "messages/message", message: message %>
        <% end %>
      </div>
      <div class="form">
        <%= simple_form_for [ @conversation, @message ], remote: true, authenticity_token: true do |f| %>
          <div class="type">
            <%= f.text_field :contents, label: false, placeholder: "Type your message here", class: 'type-box', autocomplete: 'off' %>
            <%= f.button :submit, "Send Message", class: 'send-button' %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

</div>
</div>