config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :conversations, only: [ :index, :show ] do
    resources :messages, only: :create
  end

  resources :pages, only: [:index, :show]
  get "/dashboard", to: 'pages#dashboard'
  resources :runners, only: [:index, :show, :edit, :update] do
    resources :requests, only: [:new, :create]
    resources :events, only: [:new, :create]
    resources :conversations, only: [:create]
  end

  resources :requests, only: [:destroy]

  resources :requests do
    post 'approve', to: 'requests#approve'
    post 'reject', to: 'requests#reject'
  end

  resource :profile, only: [:edit, :update, :show]

  resources :tracks, only: [:index, :show, :new, :create]


  put '/track/:id/like', to: 'tracks#like', as: 'like'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="footer-logo">We Run</p>
   <%# <p><a href="mailto:werun@gmail.com" class="contact">Contact</a></p> %>

  <div class="d-flex justify-content-around footer-box">
    <div class="team-members">
      <%= link_to "https://github.com/SeyoungJoo", target: :_blank do %>
      <%= image_tag "team1.JPG", class: "avatar-large" %>
      <% end %>

      <%= link_to "https://github.com/christinejung92", target: :_blank do %>
      <%= image_tag "team2.JPG", class: "avatar-large"%>
      <% end %>

      <%= link_to "https://github.com/woid1221", target: :_blank do %>
      <%= image_tag "team4.JPG", class: "avatar-large"%>
      <% end %>

      <%= link_to "https://github.com/Jay-JYKim91", target: :_blank do %>
      <%= image_tag "team3.JPG", class: "avatar-large"%>
      <% end %>
    </div>

    <div class="le-wagon-logo">
      <%= link_to "https://www.lewagon.com", target: :_blank do %>
      <%= image_tag "lewagon.png", class: "avatar-large"%>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_info_window_track.html.erb
<%= cl_image_tag track.image.key, class: "map-runner-image", crop: :fill %>
<h3 class="map-runner-name"><%= track.name %></h3>
<p class="map-runner-info"><%=track.address %></p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
<div class="navbar navbar-expand navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg", class: "img-circle" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if @current_tab == 'Map' %>">
          <%= link_to "Map", runners_path ,class: "nav-link" %>
        </li>
         <li class="nav-item <%= 'active' if @current_tab == 'Tracks' %>">
          <%= link_to "Tracks", tracks_path,class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if @current_tab == 'Messages' %>">
          <%= link_to "Messages", conversations_path, class: "nav-link" %>
        </li>
          <li class="nav-item <%= 'active' if @current_tab == 'Calendar' %>">
          <%= link_to "Profile", profile_path,class: "nav-link" %>
        </li>
        
        <li class="nav-item dropdown">
         <% if current_user.image.attached? %>
          <% if @pending_requests.count == 0 %>
            <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <span class="badge badge-pill badge-primary">
              <%= @pending_requests.count %>
            </span>
            <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
         <% else %>
          <%= image_tag "logo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
         <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
<div class="navbar navbar-expand navbar-lewagon2">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg", class: "img-circle" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Map", runners_path ,class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Tracks", tracks_path,class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Messages", conversations_path, class: "nav-link" %>
        </li>
          <li class="nav-item">
          <%= link_to "Profile", profile_path,class: "nav-link" %>
        </li>
        
        <li class="nav-item dropdown">
        <% if current_user.image.attached? %>
          <% if @pending_requests.count == 0 %>
            <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <span class="badge badge-pill badge-primary">
              <%= @pending_requests.count %>
            </span>
            <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
         <% else %>
          <%= image_tag "logo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
         <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/shared/_runner_popup.html.erb
     <%# popup-card %>
             <div class="popup-card" id="popup-card">
         <% @runners.each do |runner| %>
   
           <span class="close">x</span>
          <%= cl_image_tag runner.image.key, crop: :fill, class: "runner-card-img" %>
          <div class="runner-card-body">
          <strong><%= runner.first_name%> <%= runner.last_name%></strong>        
          <%= runner.introduction%>
          <%=link_to "Buddy request",
            runner_requests_path(runner),
            method: :post,
            data: { confirm: "Do you want to send a buddy request?", commit: 'Sure!' },
            class: "btn btn-md btn-primary buddy-request-button"
          %>
        </div>
      
      <% end %>
        </div>



      
     <div class="col-4 runner-cards">
        <% @runners.each do |runner| %>
          <% if runner == current_user %>
          <% else %>
           <div class="runner-card" id="runner-click" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%=Cloudinary::Utils.cloudinary_url(runner.image.key)%>'); "data-marker-id="<%= runner.id %>">
            <strong><%= runner.first_name%> <%= runner.last_name%></strong>
            </div>
          <% end %>
        <% end %>
        <%= render 'shared/runner_popup' %>
     </div>

app/views/shared/_search.html.erb
<%= form_tag runners_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "input-box",
    placeholder: "Where do you live?",
    autocomplete: 'off'
  %>

  <%= button_tag(type: "submit", class: "btn btn-lg btn-primary find-button") do %>
Find
  <% end %>
<% end %>