config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :conversations, only: [ :index, :show ] do
    resources :messages, only: :create
  end

  resources :pages, only: [:index, :show]
  get "/dashboard", to: 'pages#dashboard'
  resources :runners, only: [:index, :show, :edit, :update] do
    resources :requests, only: [:new, :create]
    resources :events, only: [:new, :create]
    resources :conversations, only: [:create]
  end

  resources :requests, only: [:destroy]

  resources :requests do
    post 'approve', to: 'requests#approve'
    post 'reject', to: 'requests#reject'
  end

  resource :profile, only: [:edit, :update, :show]

  resources :tracks, only: [:index, :show, :new, :create]


  put '/track/:id/like', to: 'tracks#like', as: 'like'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :receiver, foreign_key: :receiver_id, class_name: 'User'
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @requests = policy_scope(Request).order(created_at: :desc)
    @user = policy_scope(User).order(created_at: :desc)

    @received_requests = current_user.received_requests
    @pending_requests =[]

    @received_requests.each do |request|
      if request.status == "Pending"
        @pending_requests.push(request)
      end
    end
  end

  def new
    @request = Request.new

    @receiver = User.find(params[:runner_id])
    @sender = current_user

    authorize @request
  end

  def create
    @request = Request.new
    @receiver = User.find(params[:runner_id])
    @request.sender_id = current_user.id
    @request.receiver_id = @receiver.id
    @request.status = 'Pending'

    if @request.save
      redirect_to profile_path
    else
      render :new
    end

    authorize @request
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    redirect_to profile_path
    authorize @request
  end

  def approve
    @request = Request.find(params[:request_id])
    @request.status = "Approved"
    @request.save

    redirect_to profile_path
    authorize @request
  end

  def reject
    @request = Request.find(params[:request_id])
    @request.status = "Rejected"
    @request.save

    redirect_to profile_path
    authorize @request
  end

  private

  def request_params
    params.require(:request).permit(:start_time, :end_time)
  end
end

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/new.html.erb
<div class="container">
  <h1>Do you want to run with <%= @receiver.first_name %>?</h1>

  <%= simple_form_for [ @receiver, @request ], url: runner_requests_path do |f| %>
    <%= f.input :start_time, as: :string, required: true, input_html: {class: "datepicker"} %>
    <%= f.input :end_time, as: :string, required: true, input_html: {class: "datepicker"} %>
    <%= f.submit "Send request" %>
  <% end %>

</div>

app/views/requests/update.html.erb
<h1>Requests#update</h1>
<p>Find me in app/views/requests/update.html.erb</p>